# SPDX-License-Identifier: Apache-2.0
"""TestBoost persistent installer.

Installs TestBoost slash commands and wrapper scripts into a target Java
project so that LLM CLIs (Claude Code, OpenCode) call the real TestBoost
CLI with resolved paths.

What gets installed in the target project:

    <project>/
    ├── .claude/commands/testboost.*.md   # Claude Code slash commands
    ├── .opencode/commands/testboost.*.md # OpenCode slash commands
    └── .testboost/
        ├── scripts/tb-*.sh|ps1           # Wrapper scripts with absolute paths
        ├── .tb_secret                     # Integrity token secret
        └── config.yaml                    # TestBoost configuration
"""

import re
import stat
from pathlib import Path
from typing import Any

# Template placeholders
TESTBOOST_ROOT_PLACEHOLDER = "{{TESTBOOST_ROOT}}"
SCRIPT_PATH_PLACEHOLDER = "scripts/tb-"

VALID_SHELL_TYPES = ("bash", "powershell")


def install_commands(
    project_path: str,
    testboost_root: str,
    shell_type: str = "bash",
) -> dict[str, Any]:
    """Install TestBoost commands and scripts into a target project.

    Args:
        project_path: Absolute path to the target Java project.
        testboost_root: Absolute path to the TestBoost installation.
        shell_type: Shell type for wrapper scripts ("bash" or "powershell").

    Returns:
        Dict with success status and details.
    """
    if shell_type not in VALID_SHELL_TYPES:
        return {
            "success": False,
            "message": f"Invalid shell type '{shell_type}'. Must be one of: {', '.join(VALID_SHELL_TYPES)}",
        }

    project = Path(project_path).resolve()
    tb_root = Path(testboost_root).resolve()

    if not project.exists():
        return {"success": False, "message": f"Project path does not exist: {project}"}

    details = []

    # 1. Install wrapper scripts to .testboost/scripts/
    details.extend(_install_scripts(project, tb_root, shell_type))

    # 2. Install slash commands for Claude Code (.claude/commands/)
    details.extend(_install_commands_for_cli(project, tb_root, ".claude", shell_type))

    # 3. Install slash commands for OpenCode (.opencode/commands/)
    details.extend(_install_commands_for_cli(project, tb_root, ".opencode", shell_type))

    # 4. Create integrity secret
    from src.lib.integrity import get_or_create_secret
    get_or_create_secret(str(project))
    details.append("Created integrity secret in .testboost/.tb_secret")

    return {
        "success": True,
        "message": f"TestBoost commands installed in {project} (shell: {shell_type})",
        "details": details,
    }


def _install_scripts(project: Path, tb_root: Path, shell_type: str) -> list[str]:
    """Install wrapper shell scripts that point to the TestBoost installation."""
    scripts_dir = project / ".testboost" / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    steps = ["init", "analyze", "gaps", "generate", "validate", "verify", "status"]
    details = []

    if shell_type == "powershell":
        for step in steps:
            script_content = _generate_wrapper_script_ps1(step, tb_root)
            script_path = scripts_dir / f"tb-{step}.ps1"
            script_path.write_text(script_content, encoding="utf-8")
            details.append(f"Wrote .testboost/scripts/tb-{step}.ps1")
    else:
        for step in steps:
            script_content = _generate_wrapper_script_bash(step, tb_root)
            script_path = scripts_dir / f"tb-{step}.sh"
            script_path.write_text(script_content, encoding="utf-8")
            # Make executable
            script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
            details.append(f"Wrote .testboost/scripts/tb-{step}.sh")

    return details


def _generate_wrapper_script_bash(step: str, tb_root: Path) -> str:
    """Generate a bash wrapper shell script with resolved paths."""
    return f"""#!/usr/bin/env bash
# TestBoost - {step} (installed wrapper)
# Auto-generated by: testboost install
# TestBoost installation: {tb_root}
set -euo pipefail

TESTBOOST_ROOT="{tb_root}"

# Activate virtual environment
if [ -f "$TESTBOOST_ROOT/.venv/bin/activate" ]; then
    source "$TESTBOOST_ROOT/.venv/bin/activate"
elif [ -f "$TESTBOOST_ROOT/.venv/Scripts/activate" ]; then
    source "$TESTBOOST_ROOT/.venv/Scripts/activate"
elif [ -f "$TESTBOOST_ROOT/venv/bin/activate" ]; then
    source "$TESTBOOST_ROOT/venv/bin/activate"
fi

PROJECT_PATH="${{1:?Usage: tb-{step}.sh <project_path> [options]}}"
shift

cd "$TESTBOOST_ROOT"
python -m testboost {step} "$PROJECT_PATH" "$@"
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo ""
    echo "[TESTBOOST_FAILED:exit_code=$EXIT_CODE:step={step}]"
    echo "CRITICAL: TestBoost command '{step}' failed. Do NOT proceed with this step manually."
fi

exit $EXIT_CODE
"""


def _generate_wrapper_script_ps1(step: str, tb_root: Path) -> str:
    """Generate a PowerShell wrapper script with resolved paths."""
    return f"""# TestBoost - {step} (installed wrapper)
# Auto-generated by: testboost install
# TestBoost installation: {tb_root}
param(
    [Parameter(Mandatory=$true, Position=0)]
    [string]$ProjectPath,
    [Parameter(ValueFromRemainingArguments=$true)]
    [string[]]$ExtraArgs
)
$ErrorActionPreference = "Stop"

$TestBoostRoot = "{tb_root}"

# Activate virtual environment
if (Test-Path "$TestBoostRoot\\.venv\\Scripts\\Activate.ps1") {{
    & "$TestBoostRoot\\.venv\\Scripts\\Activate.ps1"
}} elseif (Test-Path "$TestBoostRoot\\venv\\Scripts\\Activate.ps1") {{
    & "$TestBoostRoot\\venv\\Scripts\\Activate.ps1"
}}

Push-Location $TestBoostRoot
try {{
    python -m testboost {step} $ProjectPath @ExtraArgs
    $exitCode = $LASTEXITCODE
}} finally {{
    Pop-Location
}}

if ($exitCode -ne 0) {{
    Write-Host ""
    Write-Host "[TESTBOOST_FAILED:exit_code=$exitCode:step={step}]"
    Write-Host "CRITICAL: TestBoost command '{step}' failed. Do NOT proceed with this step manually."
}}

exit $exitCode
"""


def _install_commands_for_cli(
    project: Path, tb_root: Path, cli_dir_name: str, shell_type: str,
) -> list[str]:
    """Install slash command markdown files for a specific LLM CLI."""
    templates_dir = tb_root / "templates" / "commands"
    if not templates_dir.exists():
        return [f"Warning: Templates not found at {templates_dir}"]

    target_dir = project / cli_dir_name / "commands"
    target_dir.mkdir(parents=True, exist_ok=True)

    details = []

    for template_file in sorted(templates_dir.glob("testboost.*.md")):
        content = template_file.read_text(encoding="utf-8")

        if shell_type == "powershell":
            # Replace bash invocations with powershell invocations
            # e.g., "bash scripts/tb-generate.sh" becomes
            #        "powershell -ExecutionPolicy Bypass -File .testboost/scripts/tb-generate.ps1"
            content = re.sub(
                r"bash scripts/(tb-\w+)\.sh",
                r"powershell -ExecutionPolicy Bypass -File .testboost/scripts/\1.ps1",
                content,
            )
            # Also update the code fence language hints
            content = re.sub(
                r"```bash\n(powershell )",
                r"```powershell\n\1",
                content,
            )
        else:
            # Replace relative script paths with absolute paths to installed scripts
            # e.g., "bash scripts/tb-generate.sh" becomes
            #        "bash .testboost/scripts/tb-generate.sh"
            content = re.sub(
                r"bash scripts/(tb-\w+\.sh)",
                r"bash .testboost/scripts/\1",
                content,
            )

        target_file = target_dir / template_file.name
        target_file.write_text(content, encoding="utf-8")
        details.append(f"Wrote {cli_dir_name}/commands/{template_file.name}")

    return details
