"""Initial migration with all models

Revision ID: 602dd0971fff
Revises:
Create Date: 2025-11-28 14:25:36.881877

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "602dd0971fff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("build_system", sa.Enum("MAVEN", "GRADLE", name="buildsystem"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", "ANALYZING", "UPDATING", "ERROR", name="projectstatus"),
            nullable=False,
        ),
        sa.Column("java_version", sa.String(length=50), nullable=True),
        sa.Column("pom_path", sa.String(length=512), nullable=False),
        sa.Column("repository_url", sa.String(length=1024), nullable=True),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("last_analyzed", sa.DateTime(), nullable=True),
        sa.Column("analysis_config", sa.JSON(), nullable=True),
        sa.Column("project_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("project_path", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sessions_created_at", "sessions", ["created_at"], unique=False)
    op.create_index("ix_sessions_project_path", "sessions", ["project_path"], unique=False)
    op.create_index("ix_sessions_status", "sessions", ["status"], unique=False)
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.String(length=255), nullable=False),
        sa.Column("artifact_id", sa.String(length=255), nullable=False),
        sa.Column("current_version", sa.String(length=100), nullable=False),
        sa.Column("latest_version", sa.String(length=100), nullable=True),
        sa.Column(
            "scope",
            sa.Enum(
                "COMPILE", "PROVIDED", "RUNTIME", "TEST", "SYSTEM", "IMPORT", name="dependencyscope"
            ),
            nullable=False,
        ),
        sa.Column(
            "update_status",
            sa.Enum("CURRENT", "UPDATE_AVAILABLE", "VULNERABLE", "UNKNOWN", name="updatestatus"),
            nullable=False,
        ),
        sa.Column("is_direct", sa.Boolean(), nullable=False),
        sa.Column("is_managed", sa.Boolean(), nullable=False),
        sa.Column("vulnerabilities", sa.JSON(), nullable=True),
        sa.Column("release_notes_url", sa.String(length=1024), nullable=True),
        sa.Column("last_checked", sa.DateTime(), nullable=True),
        sa.Column("dep_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dependencies_artifact_id"), "dependencies", ["artifact_id"], unique=False
    )
    op.create_index(op.f("ix_dependencies_group_id"), "dependencies", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_dependencies_project_id"), "dependencies", ["project_id"], unique=False
    )
    op.create_table(
        "modifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column(
            "modification_type",
            sa.Enum(
                "DEPENDENCY_UPDATE",
                "DEPENDENCY_ADD",
                "DEPENDENCY_REMOVE",
                "PROPERTY_CHANGE",
                "PLUGIN_UPDATE",
                "CONFIG_CHANGE",
                name="modificationtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPLIED",
                "VALIDATED",
                "ROLLED_BACK",
                "FAILED",
                name="modificationstatus",
            ),
            nullable=False,
        ),
        sa.Column("target", sa.String(length=512), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=1024), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("validation_result", sa.JSON(), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("mod_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modifications_project_id"), "modifications", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_modifications_session_id"), "modifications", ["session_id"], unique=False
    )
    op.create_table(
        "project_locks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_path", sa.Text(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_path"),
    )
    op.create_index("ix_project_locks_expires_at", "project_locks", ["expires_at"], unique=False)
    op.create_index(
        "ix_project_locks_project_path", "project_locks", ["project_path"], unique=False
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_steps_sequence", "steps", ["session_id", "sequence"], unique=False)
    op.create_index("ix_steps_session_id", "steps", ["session_id"], unique=False)
    op.create_index("ix_steps_status", "steps", ["status"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_artifacts_artifact_type", "artifacts", ["artifact_type"], unique=False)
    op.create_index("ix_artifacts_session_id", "artifacts", ["session_id"], unique=False)
    op.create_index("ix_artifacts_step_id", "artifacts", ["step_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_event_type", "events", ["event_type"], unique=False)
    op.create_index("ix_events_session_id", "events", ["session_id"], unique=False)
    op.create_index("ix_events_step_id", "events", ["step_id"], unique=False)
    op.create_index("ix_events_timestamp", "events", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_timestamp", table_name="events")
    op.drop_index("ix_events_step_id", table_name="events")
    op.drop_index("ix_events_session_id", table_name="events")
    op.drop_index("ix_events_event_type", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_artifacts_step_id", table_name="artifacts")
    op.drop_index("ix_artifacts_session_id", table_name="artifacts")
    op.drop_index("ix_artifacts_artifact_type", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index("ix_steps_status", table_name="steps")
    op.drop_index("ix_steps_session_id", table_name="steps")
    op.drop_index("ix_steps_sequence", table_name="steps")
    op.drop_table("steps")
    op.drop_index("ix_project_locks_project_path", table_name="project_locks")
    op.drop_index("ix_project_locks_expires_at", table_name="project_locks")
    op.drop_table("project_locks")
    op.drop_index(op.f("ix_modifications_session_id"), table_name="modifications")
    op.drop_index(op.f("ix_modifications_project_id"), table_name="modifications")
    op.drop_table("modifications")
    op.drop_index(op.f("ix_dependencies_project_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_group_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_artifact_id"), table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index("ix_sessions_status", table_name="sessions")
    op.drop_index("ix_sessions_project_path", table_name="sessions")
    op.drop_index("ix_sessions_created_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
